version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: product  
         identifier: raw_gz_product
         description: products of Greenweez
         columns:
          - name: products_id
            description: 1ere facon de faire les tests sur schema  
            tests:
              - unique:
                  column_name: products_id
              - not_null:
                  column_name: products_id
       - name: sales
         identifier: raw_gz_sales 
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: date_date
         columns:
           - name: date_date
             description: date of purchase 
         tests:
           - unique:
              column_name: "concat(orders_id, '-', pdt_id)"
       - name: ship
         identifier: raw_gz_ship
         columns:
          - name: orders_id
            data_tests:
              - unique
              - not_null
            description: 2e facon de faire les tests sur schema

       - name: adwords
         identifier: raw_gz_adwords
       - name: facebook
         identifier: raw_gz_facebook
       - name: criteo
         identifier: raw_gz_criteo
       - name: bing
         identifier: raw_gz_bing
         

